//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class availablegames
    {
        public int ID_availablegames { get; set; }
        public int place_ID { get; set; }
        public int games_ID { get; set; }
    
        public virtual games games { get; set; }
        public virtual place place { get; set; }
    }
}
