//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class availableroles
    {
        public int ID_availableroles { get; set; }
        public int roles_ID { get; set; }
        public int staff_ID { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual staff staff { get; set; }
    }
}
