//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClubEntities : DbContext
    {
        public ClubEntities()
            : base("name=ClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<availablegames> availablegames { get; set; }
        public virtual DbSet<availableroles> availableroles { get; set; }
        public virtual DbSet<buyers> buyers { get; set; }
        public virtual DbSet<devices> devices { get; set; }
        public virtual DbSet<extrainformation> extrainformation { get; set; }
        public virtual DbSet<games> games { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<place> place { get; set; }
        public virtual DbSet<promotion> promotion { get; set; }
        public virtual DbSet<promotionparticipant> promotionparticipant { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sessionlengths> sessionlengths { get; set; }
        public virtual DbSet<specifications> specifications { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<technicalproblems> technicalproblems { get; set; }
        public virtual DbSet<typeofproblem> typeofproblem { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
    }
}
