//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int ID_orders { get; set; }
        public int totalamount { get; set; }
        public System.TimeSpan startime { get; set; }
        public System.TimeSpan endtime { get; set; }
        public int sessionlengths_ID { get; set; }
        public int promotion_ID { get; set; }
        public int place_ID { get; set; }
    
        public virtual place place { get; set; }
        public virtual promotion promotion { get; set; }
        public virtual sessionlengths sessionlengths { get; set; }
    }
}
