//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotionparticipant
    {
        public int ID_promotionparticipant { get; set; }
        public int buyers_ID { get; set; }
        public int promotion_ID { get; set; }
    
        public virtual buyers buyers { get; set; }
        public virtual promotion promotion { get; set; }
    }
}
