//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class specifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public specifications()
        {
            this.place = new HashSet<place>();
        }
    
        public int ID_specifications { get; set; }
        public string processor { get; set; }
        public string motherboard { get; set; }
        public string computercase { get; set; }
        public string videocard { get; set; }
        public string cpucooling { get; set; }
        public string ram { get; set; }
        public string datastorage { get; set; }
        public string powersuppply { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<place> place { get; set; }
    }
}
