//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.availableroles = new HashSet<availableroles>();
        }
    
        public int ID_staff { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public int extrainformation_ID { get; set; }
        public string username { get; set; }
        public string passwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<availableroles> availableroles { get; set; }
        public virtual extrainformation extrainformation { get; set; }
    }
}
