//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class technicalproblems
    {
        public int ID_technicalproblems { get; set; }
        public int typeofproblem_ID { get; set; }
        public string descriptionofproblem { get; set; }
        public string applicationstatus { get; set; }
        public int place_ID { get; set; }
        public int roles_ID { get; set; }
        public int warehouse_ID { get; set; }
    
        public virtual place place { get; set; }
        public virtual roles roles { get; set; }
        public virtual typeofproblem typeofproblem { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
