//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD5
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warehouse()
        {
            this.technicalproblems = new HashSet<technicalproblems>();
        }
    
        public int ID_warehouse { get; set; }
        public string nameofwarehouse { get; set; }
        public string processor { get; set; }
        public string motherboard { get; set; }
        public string computercase { get; set; }
        public string videocard { get; set; }
        public string cpucooling { get; set; }
        public string ram { get; set; }
        public string datastorage { get; set; }
        public string powersuppply { get; set; }
        public string mouse { get; set; }
        public string headphones { get; set; }
        public string keyboard { get; set; }
        public string microphone { get; set; }
        public string screen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<technicalproblems> technicalproblems { get; set; }
    }
}
